# fly.toml app configuration file generated for forkgrade on 2026-03-28T16:19:18-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'forkgrade'
primary_region = 'ewr'

[build]

[deploy]
  release_command = 'python3 -c "from app import create_app; from app.db import db; app = create_app(); ctx = app.app_context(); ctx.push(); db.create_all()"'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 50
    soft_limit = 25

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
