# Google Places API (New) type → category/cuisine bucket mappings.
# Source: https://developers.google.com/maps/documentation/places/web-service/place-types

# Google Places types → our category buckets (checked in order, first match wins).
CATEGORY_TYPE_MAP = {
    # ── Healthcare ──────────────────────────────────────────────────────────
    "hospital":                     "healthcare",
    "general_hospital":             "healthcare",
    "emergency_room":               "healthcare",
    "nursing_home":                 "healthcare",
    "assisted_living_facility":     "healthcare",
    "rehabilitation_center":        "healthcare",
    "medical_clinic":               "healthcare",
    "medical_center":               "healthcare",
    "medical_lab":                  "healthcare",
    "dental_clinic":                "healthcare",
    "dentist":                      "healthcare",
    "doctor":                       "healthcare",
    "chiropractor":                 "healthcare",
    "physiotherapist":              "healthcare",
    "optometrist":                  "healthcare",
    "eye_care_clinic":              "healthcare",
    "skin_care_clinic":             "healthcare",
    "pharmacy":                     "healthcare",
    "drugstore":                    "healthcare",
    "urgent_care_facility":         "healthcare",
    "mental_health_clinic":         "healthcare",
    "adult_day_care_center":        "healthcare",
    "dialysis_center":              "healthcare",
    "hospice":                      "healthcare",
    "wellness_center":              "healthcare",
    "massage":                      "healthcare",
    "massage_spa":                  "healthcare",
    "health":                       "healthcare",   # Table B catch-all

    # ── School / childcare ───────────────────────────────────────────────────
    "school":                       "school",
    "educational_institution":      "school",
    "primary_school":               "school",
    "elementary_school":            "school",
    "middle_school":                "school",
    "secondary_school":             "school",
    "high_school":                  "school",
    "university":                   "school",
    "preschool":                    "school",
    "childcare_agency":             "school",
    "child_care_agency":            "school",
    "day_care_center":              "school",
    "tutoring_center":              "school",
    "vocational_school":            "school",
    "summer_camp_organizer":        "school",

    # ── Grocery / retail food ────────────────────────────────────────────────
    "grocery_or_supermarket":       "grocery",
    "supermarket":                  "grocery",
    "grocery_store":                "grocery",
    "asian_grocery_store":          "grocery",
    "discount_supermarket":         "grocery",
    "hypermarket":                  "grocery",
    "warehouse_store":              "grocery",
    "convenience_store":            "grocery",
    "food_store":                   "grocery",
    "health_food_store":            "grocery",
    "butcher_shop":                 "grocery",
    "farmers_market":               "grocery",
    "market":                       "grocery",
    "liquor_store":                 "grocery",
    "wholesaler":                   "grocery",

    # ── Caterer ──────────────────────────────────────────────────────────────
    "catering_service":             "caterer",
    "food_delivery":                "caterer",
    "meal_delivery":                "caterer",

    # ── Restaurant / food service (all Table A food types) ───────────────────
    # Generic
    "restaurant":                   "restaurant",
    "meal_takeaway":                "restaurant",
    "food_court":                   "restaurant",
    "cafeteria":                    "restaurant",
    "buffet_restaurant":            "restaurant",
    "fast_food_restaurant":         "restaurant",
    "fine_dining_restaurant":       "restaurant",
    "family_restaurant":            "restaurant",
    "fusion_restaurant":            "restaurant",
    "bistro":                       "restaurant",
    "diner":                        "restaurant",
    "snack_bar":                    "restaurant",
    "halal_restaurant":             "restaurant",
    "vegan_restaurant":             "restaurant",
    "vegetarian_restaurant":        "restaurant",
    # Cafes / drinks
    "cafe":                         "restaurant",
    "coffee_shop":                  "restaurant",
    "coffee_roastery":              "restaurant",
    "coffee_stand":                 "restaurant",
    "juice_shop":                   "restaurant",
    "tea_house":                    "restaurant",
    "acai_shop":                    "restaurant",
    # Bakery / sweets
    "bakery":                       "restaurant",
    "bagel_shop":                   "restaurant",
    "cake_shop":                    "restaurant",
    "pastry_shop":                  "restaurant",
    "donut_shop":                   "restaurant",
    "dessert_restaurant":           "restaurant",
    "dessert_shop":                 "restaurant",
    "confectionery":                "restaurant",
    "candy_store":                  "restaurant",
    "chocolate_factory":            "restaurant",
    "chocolate_shop":               "restaurant",
    "ice_cream_shop":               "restaurant",
    # Bars / nightlife
    "bar":                          "restaurant",
    "bar_and_grill":                "restaurant",
    "pub":                          "restaurant",
    "irish_pub":                    "restaurant",
    "sports_bar":                   "restaurant",
    "cocktail_bar":                 "restaurant",
    "wine_bar":                     "restaurant",
    "lounge_bar":                   "restaurant",
    "hookah_bar":                   "restaurant",
    "beer_garden":                  "restaurant",
    "night_club":                   "restaurant",
    "gastropub":                    "restaurant",
    # Breweries / wineries
    "brewery":                      "restaurant",
    "brewpub":                      "restaurant",
    "winery":                       "restaurant",
    "vineyard":                     "restaurant",
    "distillery":                   "restaurant",
    # Deli / sandwiches
    "deli":                         "restaurant",
    "sandwich_shop":                "restaurant",
    "salad_shop":                   "restaurant",
    # Pizza
    "pizza_restaurant":             "restaurant",
    "pizza_delivery":               "restaurant",
    # American
    "american_restaurant":          "restaurant",
    "hamburger_restaurant":         "restaurant",
    "steak_house":                  "restaurant",
    "barbecue_restaurant":          "restaurant",
    "chicken_restaurant":           "restaurant",
    "chicken_wings_restaurant":     "restaurant",
    "hot_dog_restaurant":           "restaurant",
    "hot_dog_stand":                "restaurant",
    "soul_food_restaurant":         "restaurant",
    "cajun_restaurant":             "restaurant",
    "californian_restaurant":       "restaurant",
    "southwestern_us_restaurant":   "restaurant",
    "hawaiian_restaurant":          "restaurant",
    "western_restaurant":           "restaurant",
    # Italian
    "italian_restaurant":           "restaurant",
    # Mexican / Latin
    "mexican_restaurant":           "restaurant",
    "latin_american_restaurant":    "restaurant",
    "brazilian_restaurant":         "restaurant",
    "caribbean_restaurant":         "restaurant",
    "cuban_restaurant":             "restaurant",
    "colombian_restaurant":         "restaurant",
    "peruvian_restaurant":          "restaurant",
    "south_american_restaurant":    "restaurant",
    "argentinian_restaurant":       "restaurant",
    "chilean_restaurant":           "restaurant",
    "burrito_restaurant":           "restaurant",
    "taco_restaurant":              "restaurant",
    "tex_mex_restaurant":           "restaurant",
    # Japanese
    "japanese_restaurant":          "restaurant",
    "sushi_restaurant":             "restaurant",
    "ramen_restaurant":             "restaurant",
    "japanese_curry_restaurant":    "restaurant",
    "japanese_izakaya_restaurant":  "restaurant",
    "tonkatsu_restaurant":          "restaurant",
    "yakiniku_restaurant":          "restaurant",
    "yakitori_restaurant":          "restaurant",
    # Chinese
    "chinese_restaurant":           "restaurant",
    "cantonese_restaurant":         "restaurant",
    "chinese_noodle_restaurant":    "restaurant",
    "dim_sum_restaurant":           "restaurant",
    "dumpling_restaurant":          "restaurant",
    "hot_pot_restaurant":           "restaurant",
    "mongolian_barbecue_restaurant":"restaurant",
    "taiwanese_restaurant":         "restaurant",
    "noodle_shop":                  "restaurant",
    # Thai / Southeast Asian
    "thai_restaurant":              "restaurant",
    "vietnamese_restaurant":        "restaurant",
    "indonesian_restaurant":        "restaurant",
    "malaysian_restaurant":         "restaurant",
    "cambodian_restaurant":         "restaurant",
    "filipino_restaurant":          "restaurant",
    "burmese_restaurant":           "restaurant",
    "sri_lankan_restaurant":        "restaurant",
    # Indian / South Asian
    "indian_restaurant":            "restaurant",
    "north_indian_restaurant":      "restaurant",
    "south_indian_restaurant":      "restaurant",
    "pakistani_restaurant":         "restaurant",
    "bangladeshi_restaurant":       "restaurant",
    # Greek / Mediterranean / Middle Eastern
    "greek_restaurant":             "restaurant",
    "mediterranean_restaurant":     "restaurant",
    "middle_eastern_restaurant":    "restaurant",
    "lebanese_restaurant":          "restaurant",
    "turkish_restaurant":           "restaurant",
    "persian_restaurant":           "restaurant",
    "moroccan_restaurant":          "restaurant",
    "israeli_restaurant":           "restaurant",
    "afghani_restaurant":           "restaurant",
    "falafel_restaurant":           "restaurant",
    "gyro_restaurant":              "restaurant",
    "kebab_shop":                   "restaurant",
    "shawarma_restaurant":          "restaurant",
    # Seafood
    "seafood_restaurant":           "restaurant",
    "fish_and_chips_restaurant":    "restaurant",
    "oyster_bar_restaurant":        "restaurant",
    # Breakfast / cafe-style
    "breakfast_restaurant":         "restaurant",
    "brunch_restaurant":            "restaurant",
    # European / other
    "french_restaurant":            "restaurant",
    "spanish_restaurant":           "restaurant",
    "tapas_restaurant":             "restaurant",
    "basque_restaurant":            "restaurant",
    "german_restaurant":            "restaurant",
    "austrian_restaurant":          "restaurant",
    "bavarian_restaurant":          "restaurant",
    "swiss_restaurant":             "restaurant",
    "belgian_restaurant":           "restaurant",
    "dutch_restaurant":             "restaurant",
    "danish_restaurant":            "restaurant",
    "scandinavian_restaurant":      "restaurant",
    "british_restaurant":           "restaurant",
    "irish_restaurant":             "restaurant",
    "polish_restaurant":            "restaurant",
    "croatian_restaurant":          "restaurant",
    "czech_restaurant":             "restaurant",
    "hungarian_restaurant":         "restaurant",
    "romanian_restaurant":          "restaurant",
    "ukrainian_restaurant":         "restaurant",
    "russian_restaurant":           "restaurant",
    "eastern_european_restaurant":  "restaurant",
    "european_restaurant":          "restaurant",
    "portuguese_restaurant":        "restaurant",
    # Other Asian
    "korean_restaurant":            "restaurant",
    "korean_barbecue_restaurant":   "restaurant",
    "tibetan_restaurant":           "restaurant",
    "asian_restaurant":             "restaurant",
    "asian_fusion_restaurant":      "restaurant",
    # African / other
    "african_restaurant":           "restaurant",
    "ethiopian_restaurant":         "restaurant",
    "australian_restaurant":        "restaurant",
    # Misc food
    "soup_restaurant":              "restaurant",
    "fondue_restaurant":            "restaurant",
    "dog_cafe":                     "restaurant",
    "cat_cafe":                     "restaurant",
}

# Google Places types → cuisine buckets (for restaurant locations)
CUISINE_TYPE_MAP = {
    # Pizza
    "pizza_restaurant":             "pizza",
    "pizza_delivery":               "pizza",
    # Italian
    "italian_restaurant":           "italian",
    # Japanese
    "japanese_restaurant":          "japanese",
    "sushi_restaurant":             "japanese",
    "ramen_restaurant":             "japanese",
    "japanese_curry_restaurant":    "japanese",
    "japanese_izakaya_restaurant":  "japanese",
    "tonkatsu_restaurant":          "japanese",
    "yakiniku_restaurant":          "japanese",
    "yakitori_restaurant":          "japanese",
    # Chinese
    "chinese_restaurant":           "chinese",
    "cantonese_restaurant":         "chinese",
    "chinese_noodle_restaurant":    "chinese",
    "dim_sum_restaurant":           "chinese",
    "dumpling_restaurant":          "chinese",
    "hot_pot_restaurant":           "chinese",
    "mongolian_barbecue_restaurant":"chinese",
    "taiwanese_restaurant":         "chinese",

    # Mexican / Latin
    "mexican_restaurant":           "mexican",
    "latin_american_restaurant":    "mexican",
    "brazilian_restaurant":         "mexican",
    "caribbean_restaurant":         "mexican",
    "cuban_restaurant":             "mexican",
    "colombian_restaurant":         "mexican",
    "peruvian_restaurant":          "mexican",
    "south_american_restaurant":    "mexican",
    "argentinian_restaurant":       "mexican",
    "chilean_restaurant":           "mexican",
    "burrito_restaurant":           "mexican",
    "taco_restaurant":              "mexican",
    "tex_mex_restaurant":           "mexican",
    # Thai
    "thai_restaurant":              "thai",
    # Indian / South Asian
    "indian_restaurant":            "indian",
    "north_indian_restaurant":      "indian",
    "south_indian_restaurant":      "indian",
    "pakistani_restaurant":         "indian",
    "bangladeshi_restaurant":       "indian",
    "sri_lankan_restaurant":        "indian",
    # Greek / Mediterranean / Middle Eastern
    "greek_restaurant":             "greek",
    "mediterranean_restaurant":     "greek",
    "middle_eastern_restaurant":    "greek",
    "lebanese_restaurant":          "greek",
    "turkish_restaurant":           "greek",
    "persian_restaurant":           "greek",
    "moroccan_restaurant":          "greek",
    "israeli_restaurant":           "greek",
    "afghani_restaurant":           "greek",
    "falafel_restaurant":           "greek",
    "gyro_restaurant":              "greek",
    "kebab_shop":                   "greek",
    "shawarma_restaurant":          "greek",
    # Seafood
    "seafood_restaurant":           "seafood",
    "fish_and_chips_restaurant":    "seafood",
    "oyster_bar_restaurant":        "seafood",
    # Breakfast / cafe
    "breakfast_restaurant":         "breakfast",
    "brunch_restaurant":            "breakfast",
    "cafe":                         "breakfast",
    "coffee_shop":                  "breakfast",
    "coffee_roastery":              "breakfast",
    "coffee_stand":                 "breakfast",
    "bakery":                       "breakfast",
    "bagel_shop":                   "breakfast",
    "cake_shop":                    "breakfast",
    "pastry_shop":                  "breakfast",
    "donut_shop":                   "breakfast",
    "juice_shop":                   "breakfast",
    "tea_house":                    "breakfast",
    "acai_shop":                    "breakfast",
    # American
    "american_restaurant":          "american",
    "hamburger_restaurant":         "american",
    "steak_house":                  "american",
    "barbecue_restaurant":          "american",
    "fast_food_restaurant":         "american",
    "chicken_restaurant":           "american",
    "chicken_wings_restaurant":     "american",
    "hot_dog_restaurant":           "american",
    "hot_dog_stand":                "american",
    "soul_food_restaurant":         "american",
    "cajun_restaurant":             "american",
    "californian_restaurant":       "american",
    "southwestern_us_restaurant":   "american",
    "hawaiian_restaurant":          "american",
    "western_restaurant":           "american",
    "sandwich_shop":                "american",
    "deli":                         "american",
    "diner":                        "american",
    "salad_shop":                   "american",
    # Bar / pub
    "bar":                          "bar",
    "bar_and_grill":                "bar",
    "pub":                          "bar",
    "irish_pub":                    "bar",
    "sports_bar":                   "bar",
    "cocktail_bar":                 "bar",
    "wine_bar":                     "bar",
    "lounge_bar":                   "bar",
    "hookah_bar":                   "bar",
    "beer_garden":                  "bar",
    "night_club":                   "bar",
    "gastropub":                    "bar",
    "brewery":                      "bar",
    "brewpub":                      "bar",
    "winery":                       "bar",
    "vineyard":                     "bar",
    "distillery":                   "bar",
}
